### ISSUE TITLE
Google play link unavailable

### ISSUE THREAD

**Issue by stonega** [filiph/tictactoe#1]

**Comment by filiph** [comment]
:) Shhh!

**Comment by filiph** [comment]
The game is supposed to "launch" tomorrow. I just want to have everything ready, so I published the code today. Please don't share this repo just yet.

And thanks for paying attention, and pro-actively filing issues!

**Comment by stonega** [comment]
I have enjoyed the game so far, will try to learn the code and maybe develop my own simple game with flutter :)
